name: todo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.1
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.4
  flutter_bloc: ^8.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_slidable: ^2.0.0
  intl: ^0.18.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.7
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/